#!/bin/bash

#kasutajad ja paroolid failist

if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 failinimi"
else
	failinimi=$1
	if [ -f $failinimi -a -r $failinimi ]; then
		echo "fail on korras"
while read rida
do
  kasutajanimi=$(echo "$rida" | cut -f1 -d:)
sh lisa_kasutaja $kasutajanimi
echo "$rida" | chpasswd
done < $failinimi
	else
		echo "Probleem failiga $failinimi"
	fi
fi

