#!/bin/bash
# kasutaja ja parooli lisamise skript

pr=0

if [ $# -ne 2 ]; then

	echo "Kasutusjuhend: $0 kasutajanimede_fail paroolide_fail"

else

	kasutajafail=$1
	paroolifail=$2

	if [ -f $kasutajafail -a -r $kasutajafail ]; then
		echo "kasutajate fail on korras"

	        if [ -f $paroolifail -a -r $paroolifail ]; then
        	        echo "paroolide fail on korras"
			for nimi in $(cat $kasutajafail)
			do
				useradd $nimi -m -s /bin/bash
				if [ $? -eq 0 ]; then
					echo "Kasutaja nimega $nimi on lisatud süsteemi"
					cat /etc/passwd | grep $nimi
					ls -la /home/$nimi
					((pr++))
					echo "$nimi:$(sed -n "$pr"p paroolid)" | chpasswd
				else
					echo "probleem kasutaja $nimi lisamisega"
					echo "probleemi kood on $?"
				fi
			done
		else
			echo "probleem failiga $paroolifail"
		fi
	else
		echo "probleem failiga $kasutajafail"
	fi
fi


